In [29]:
import pandas as pd

ccres = pd.read_csv('/hpc/home/rv103/igvf/A549/extra_GCs/GRCh38-cCREs.bed', sep='\t',
                    names=['chr','start','end','id1','id2','labels'])

ccres['diff'] = ccres['end']-ccres['start']
# ((ccres['diff']*2)+1)
ccres['alleles']=(ccres['diff']*3)+1
ccres['alleles'].sum()

871423224

In [11]:
ccres

,chr,start,end,id1,id2,labels,diff
0,chr1,104896,105048,EH38D4327509,EH38E2776520,"CTCF-only,CTCF-bound",152
1,chr1,138866,139134,EH38D4327520,EH38E2776521,"pELS,CTCF-bound",268
2,chr1,181289,181639,EH38D4327525,EH38E2776524,"DNase-H3K4me3,CTCF-bound",350
3,chr1,267925,268171,EH38D4327544,EH38E2776528,"CTCF-only,CTCF-bound",246
4,chr1,586036,586264,EH38D4327554,EH38E2776532,"CTCF-only,CTCF-bound",228
...,...,...,...,...,...,...,...
1063873,chrY,21252996,21253278,EH38D6144481,EH38E3951203,dELS,282
1063874,chrY,21598449,21598656,EH38D6144550,EH38E3951229,"CTCF-only,CTCF-bound",207
1063875,chrY,21839503,21839853,EH38D6144588,EH38E3951242,dELS,350
1063876,chrY,26352857,26353207,EH38D4327371,EH38E3951251,pELS,350
1063877,chrY,26353315,26353520,EH38D4327372,EH38E3951252,pELS,205

In [22]:
pred = pd.read_csv('/hpc/home/rv103/igvf/revathy/IGVF_predictions/data/pred1_Dex.txt', sep='\t')
pred

,ID,actualInterval,pos,ref,allele,prediction
0,chr1:104896-105048,chr1:104746-105046,pos=104896,ref=T,G,0.665910
1,chr1:104896-105048,chr1:104746-105046,pos=104896,ref=T,C,0.656498
2,chr1:104896-105048,chr1:104746-105046,pos=104896,ref=T,A,0.660895
3,chr1:104896-105048,chr1:104746-105046,pos=104896,ref=T,T,0.684963
4,chr1:104896-105048,chr1:104747-105047,pos=104897,ref=T,G,0.700971
...,...,...,...,...,...,...
760763,chr1:2046491-2046831,chr1:2046659-2046959,pos=2046809,ref=C,A,0.685785
760764,chr1:2046491-2046831,chr1:2046659-2046959,pos=2046809,ref=C,T,0.687635
760765,chr1:2046491-2046831,chr1:2046660-2046960,pos=2046810,ref=T,G,0.679208
760766,chr1:2046491-2046831,chr1:2046660-2046960,pos=2046810,ref=T,C,0.686496
760767,chr1:2046491-2046831,chr1:2046660-2046960,pos=2046810,ref=T,A,0.687645

In [21]:
len(pred['pos'].drop_duplicates())

253256

In [27]:
(253256*3)+1000

760768

In [17]:
%%bash
cat /hpc/group/igvf/K562/CRE-preds/chunks/CREs1.txt /hpc/group/igvf/K562/CRE-preds/chunks/CREs2.txt \
    > /hpc/home/rv103/igvf/revathy/IGVF_predictions/data/CREs1_2.txt

In [4]:
105048-104896

152

In [7]:
ccres.shape

(1063878, 7)

In [8]:
1063878/1000

1063.878

In [18]:
24220806/26664186

0.9083647256286016

In [1]:
import pandas as pd

cre1 = pd.read_csv('/hpc/group/igvf/K562/CRE-preds/chunks/CREs1.txt', sep='\t')

ParserError: Error tokenizing data. C error: Expected 270 fields in line 3, saw 302

In [2]:
!head /hpc/group/igvf/K562/CRE-preds/chunks/CREs1.txt

chr1:104896-105048	104896:ref=T:G,C,A,T	104897:ref=T:G,C,A	104898:ref=T:G,C,A	104899:ref=C:G,A,T	104900:ref=A:G,C,T	104901:ref=G:C,A,T	104902:ref=A:G,C,T	104903:ref=T:G,C,A	104904:ref=C:G,A,T	104905:ref=T:G,C,A	104906:ref=C:G,A,T	104907:ref=T:G,C,A	104908:ref=A:G,C,T	104909:ref=G:C,A,T	104910:ref=A:G,C,T	104911:ref=A:G,C,T	104912:ref=C:G,A,T	104913:ref=T:G,C,A	104914:ref=A:G,C,T	104915:ref=T:G,C,A	104916:ref=C:G,A,T	104917:ref=C:G,A,T	104918:ref=A:G,C,T	104919:ref=T:G,C,A	104920:ref=C:G,A,T	104921:ref=A:G,C,T	104922:ref=G:C,A,T	104923:ref=T:G,C,A	104924:ref=G:C,A,T	104925:ref=A:G,C,T	104926:ref=A:G,C,T	104927:ref=A:G,C,T	104928:ref=T:G,C,A	104929:ref=G:C,A,T	104930:ref=G:C,A,T	104931:ref=A:G,C,T	104932:ref=T:G,C,A	104933:ref=T:G,C,A	104934:ref=G:C,A,T	104935:ref=C:G,A,T	104936:ref=A:G,C,T	104937:ref=A:G,C,T	104938:ref=A:G,C,T	104939:ref=T:G,C,A	104940:ref=A:G,C,T	104941:ref=C:G,A,T	104942:ref=A:G,C,T	104943:ref=A:G,C,T	104944:ref=A:G,C,T	104945:ref=G:C,A,T	104946:ref=A:G,C,T	104947:ref=G:C,A,T	104948:ref=T:G,C,A	104949:ref=A:G,C,T	104950:ref=A:G,C,T	104951:ref=T:G,C,A	104952:ref=A:G,C,T	104953:ref=C:G,A,T	104954:ref=C:G,A,T	104955:ref=A:G,C,T	104956:ref=T:G,C,A	104957:ref=G:C,A,T	104958:ref=T:G,C,A	104959:ref=C:G,A,T	104960:ref=A:G,C,T	104961:ref=C:G,A,T	104962:ref=T:G,C,A	104963:ref=T:G,C,A	104964:ref=A:G,C,T	104965:ref=A:G,C,T	104966:ref=G:C,A,T	104967:ref=A:G,C,T	104968:ref=A:G,C,T	104969:ref=T:G,C,A	104970:ref=A:G,C,T	104971:ref=G:C,A,T	104972:ref=A:G,C,T	104973:ref=A:G,C,T	104974:ref=T:G,C,A	104975:ref=C:G,A,T	104976:ref=A:G,C,T	104977:ref=T:G,C,A	104978:ref=G:C,A,T	104979:ref=G:C,A,T	104980:ref=A:G,C,T	104981:ref=C:G,A,T	104982:ref=G:C,A,T	104983:ref=A:G,C,T	104984:ref=G:C,A,T	104985:ref=G:C,A,T	104986:ref=C:G,A,T	104987:ref=T:G,C,A	104988:ref=G:C,A,T	104989:ref=C:G,A,T	104990:ref=C:G,A,T	104991:ref=A:G,C,T	104992:ref=C:G,A,T	104993:ref=C:G,A,T	104994:ref=T:G,C,A	104995:ref=G:C,A,T	104996:ref=C:G,A,T	104997:ref=T:G,C,A	104998:ref=G:C,A,T	104999:ref=T:G,C,A	105000:ref=T:G,C,A	105001:ref=G:C,A,T	105002:ref=G:C,A,T	105003:ref=G:C,A,T	105004:ref=G:C,A,T	105005:ref=G:C,A,T	105006:ref=C:G,A,T	105007:ref=C:G,A,T	105008:ref=A:G,C,T	105009:ref=C:G,A,T	105010:ref=T:G,C,A	105011:ref=G:C,A,T	105012:ref=C:G,A,T	105013:ref=A:G,C,T	105014:ref=G:C,A,T	105015:ref=A:G,C,T	105016:ref=A:G,C,T	105017:ref=G:C,A,T	105018:ref=A:G,C,T	105019:ref=A:G,C,T	105020:ref=A:G,C,T	105021:ref=T:G,C,A	105022:ref=T:G,C,A	105023:ref=C:G,A,T	105024:ref=C:G,A,T	105025:ref=A:G,C,T	105026:ref=G:C,A,T	105027:ref=A:G,C,T	105028:ref=A:G,C,T	105029:ref=C:G,A,T	105030:ref=A:G,C,T	105031:ref=C:G,A,T	105032:ref=T:G,C,A	105033:ref=G:C,A,T	105034:ref=G:C,A,T	105035:ref=A:G,C,T	105036:ref=C:G,A,T	105037:ref=T:G,C,A	105038:ref=G:C,A,T	105039:ref=G:C,A,T	105040:ref=A:G,C,T	105041:ref=G:C,A,T	105042:ref=A:G,C,T	105043:ref=G:C,A,T	105044:ref=C:G,A,T	105045:ref=A:G,C,T	105046:ref=C:G,A,T	105047:ref=C:G,A,T
chr1:138866-139134	138866:ref=G:G,C,A,T	138867:ref=G:C,A,T	138868:ref=C:G,A,T	138869:ref=C:G,A,T	138870:ref=T:G,C,A	138871:ref=G:C,A,T	138872:ref=G:C,A,T	138873:ref=A:G,C,T	138874:ref=G:C,A,T	138875:ref=A:G,C,T	138876:ref=A:G,C,T	138877:ref=G:C,A,T	138878:ref=C:G,A,T	138879:ref=C:G,A,T	138880:ref=C:G,A,T	138881:ref=C:G,A,T	138882:ref=C:G,A,T	138883:ref=A:G,C,T	138884:ref=T:G,C,A	138885:ref=G:C,A,T	138886:ref=A:G,C,T	138887:ref=G:C,A,T	138888:ref=G:C,A,T	138889:ref=C:G,A,T	138890:ref=A:G,C,T	138891:ref=G:C,A,T	138892:ref=A:G,C,T	138893:ref=G:C,A,T	138894:ref=G:C,A,T	138895:ref=T:G,C,A	138896:ref=T:G,C,A	138897:ref=G:C,A,T	138898:ref=G:C,A,T	138899:ref=G:C,A,T	138900:ref=C:G,A,T	138901:ref=C:G,A,T	138902:ref=T:G,C,A	138903:ref=G:C,A,T	138904:ref=T:G,C,A	138905:ref=A:G,C,T	138906:ref=G:C,A,T	138907:ref=A:G,C,T	138908:ref=C:G,A,T	138909:ref=G:C,A,T	138910:ref=C:G,A,T	138911:ref=T:G,C,A	138912:ref=G:C,A,T	138913:ref=A:G,C,T	138914:ref=C:G,A,T	138915:ref=A:G,C,T	138916:ref=G:C,A,T	138917:ref=G:C,A,T	138918:ref=A:G,C,T	138919:ref=G:C,A,T	138920:ref=G:C,A,T	138921:ref=C:G,A,T	138922:ref=A:G,C,T	138923:ref=G:C,A,T	138924:ref=G:C,A,T	138925:ref=A:G,C,T	138926:ref=G:C,A,T	138927:ref=C:G,A,T	138928:ref=T:G,C,A	138929:ref=G:C,A,T	138930:ref=G:C,A,T	138931:ref=G:C,A,T	138932:ref=C:G,A,T	138933:ref=C:G,A,T	138934:ref=T:G,C,A	138935:ref=G:C,A,T	138936:ref=G:C,A,T	138937:ref=A:G,C,T	138938:ref=C:G,A,T	138939:ref=A:G,C,T	138940:ref=G:C,A,T	138941:ref=G:C,A,T	138942:ref=T:G,C,A	138943:ref=C:G,A,T	138944:ref=A:G,C,T	138945:ref=A:G,C,T	138946:ref=C:G,A,T	138947:ref=T:G,C,A	138948:ref=T:G,C,A	138949:ref=G:C,A,T	138950:ref=A:G,C,T	138951:ref=G:C,A,T	138952:ref=G:C,A,T	138953:ref=A:G,C,T	138954:ref=G:C,A,T	138955:ref=A:G,C,T	138956:ref=T:G,C,A	138957:ref=T:G,C,A	138958:ref=T:G,C,A	138959:ref=T:G,C,A	138960:ref=G:C,A,T	138961:ref=G:C,A,T	138962:ref=G:C,A,T	138963:ref=C:G,A,T	138964:ref=C:G,A,T	138965:ref=T:G,C,A	138966:ref=T:G,C,A	138967:ref=C:G,A,T	138968:ref=A:G,C,T	138969:ref=T:G,C,A	138970:ref=A:G,C,T	138971:ref=G:C,A,T	138972:ref=G:C,A,T	138973:ref=C:G,A,T	138974:ref=C:G,A,T	138975:ref=A:G,C,T	138976:ref=C:G,A,T	138977:ref=C:G,A,T	138978:ref=A:G,C,T	138979:ref=G:C,A,T	138980:ref=G:C,A,T	138981:ref=A:G,C,T	138982:ref=G:C,A,T	138983:ref=G:C,A,T	138984:ref=C:G,A,T	138985:ref=A:G,C,T	138986:ref=G:C,A,T	138987:ref=C:G,A,T	138988:ref=A:G,C,T	138989:ref=G:C,A,T	138990:ref=T:G,C,A	138991:ref=T:G,C,A	138992:ref=G:C,A,T	138993:ref=G:C,A,T	138994:ref=G:C,A,T	138995:ref=A:G,C,T	138996:ref=C:G,A,T	138997:ref=T:G,C,A	138998:ref=A:G,C,T	138999:ref=G:C,A,T	139000:ref=A:G,C,T	139001:ref=G:C,A,T	139002:ref=A:G,C,T	139003:ref=G:C,A,T	139004:ref=T:G,C,A	139005:ref=C:G,A,T	139006:ref=T:G,C,A	139007:ref=G:C,A,T	139008:ref=A:G,C,T	139009:ref=C:G,A,T	139010:ref=T:G,C,A	139011:ref=T:G,C,A	139012:ref=G:C,A,T	139013:ref=A:G,C,T	139014:ref=G:C,A,T	139015:ref=T:G,C,A	139016:ref=A:G,C,T	139017:ref=A:G,C,T	139018:ref=G:C,A,T	139019:ref=T:G,C,A	139020:ref=T:G,C,A	139021:ref=T:G,C,A	139022:ref=T:G,C,A	139023:ref=G:C,A,T	139024:ref=G:C,A,T	139025:ref=G:C,A,T	139026:ref=C:G,A,T	139027:ref=C:G,A,T	139028:ref=C:G,A,T	139029:ref=G:C,A,T	139030:ref=G:C,A,T	139031:ref=A:G,C,T	139032:ref=G:C,A,T	139033:ref=A:G,C,T	139034:ref=T:G,C,A	139035:ref=G:C,A,T	139036:ref=A:G,C,T	139037:ref=T:G,C,A	139038:ref=G:C,A,T	139039:ref=T:G,C,A	139040:ref=C:G,A,T	139041:ref=C:G,A,T	139042:ref=T:G,C,A	139043:ref=G:C,A,T	139044:ref=G:C,A,T	139045:ref=G:C,A,T	139046:ref=A:G,C,T	139047:ref=C:G,A,T	139048:ref=A:G,C,T	139049:ref=G:C,A,T	139050:ref=G:C,A,T	139051:ref=A:G,C,T	139052:ref=G:C,A,T	139053:ref=T:G,C,A	139054:ref=T:G,C,A	139055:ref=G:C,A,T	139056:ref=G:C,A,T	139057:ref=C:G,A,T	139058:ref=C:G,A,T	139059:ref=G:C,A,T	139060:ref=T:G,C,A	139061:ref=G:C,A,T	139062:ref=G:C,A,T	139063:ref=A:G,C,T	139064:ref=G:C,A,T	139065:ref=A:G,C,T	139066:ref=G:C,A,T	139067:ref=G:C,A,T	139068:ref=C:G,A,T	139069:ref=C:G,A,T	139070:ref=A:G,C,T	139071:ref=C:G,A,T	139072:ref=C:G,A,T	139073:ref=G:C,A,T	139074:ref=T:G,C,A	139075:ref=G:C,A,T	139076:ref=A:G,C,T	139077:ref=G:C,A,T	139078:ref=G:C,A,T	139079:ref=C:G,A,T	139080:ref=A:G,C,T	139081:ref=T:G,C,A	139082:ref=A:G,C,T	139083:ref=A:G,C,T	139084:ref=G:C,A,T	139085:ref=C:G,A,T	139086:ref=T:G,C,A	139087:ref=G:C,A,T	139088:ref=G:C,A,T	139089:ref=A:G,C,T	139090:ref=T:G,C,A	139091:ref=G:C,A,T	139092:ref=T:G,C,A	139093:ref=A:G,C,T	139094:ref=G:C,A,T	139095:ref=A:G,C,T	139096:ref=G:C,A,T	139097:ref=A:G,C,T	139098:ref=G:C,A,T	139099:ref=G:C,A,T	139100:ref=C:G,A,T	139101:ref=C:G,A,T	139102:ref=A:G,C,T	139103:ref=G:C,A,T	139104:ref=T:G,C,A	139105:ref=G:C,A,T	139106:ref=T:G,C,A	139107:ref=G:C,A,T	139108:ref=A:G,C,T	139109:ref=G:C,A,T	139110:ref=G:C,A,T	139111:ref=C:G,A,T	139112:ref=A:G,C,T	139113:ref=A:G,C,T	139114:ref=G:C,A,T	139115:ref=A:G,C,T	139116:ref=C:G,A,T	139117:ref=C:G,A,T	139118:ref=T:G,C,A	139119:ref=G:C,A,T	139120:ref=G:C,A,T	139121:ref=G:C,A,T	139122:ref=C:G,A,T	139123:ref=C:G,A,T	139124:ref=T:G,C,A	139125:ref=G:C,A,T	139126:ref=T:G,C,A	139127:ref=C:G,A,T	139128:ref=T:G,C,A	139129:ref=A:G,C,T	139130:ref=G:C,A,T	139131:ref=G:C,A,T	139132:ref=C:G,A,T	139133:ref=T:G,C,A
chr1:181289-181639	181314:ref=G:G,C,A,T	181315:ref=C:G,A,T	181316:ref=G:C,A,T	181317:ref=C:G,A,T	181318:ref=C:G,A,T	181319:ref=G:C,A,T	181320:ref=C:G,A,T	181321:ref=G:C,A,T	181322:ref=C:G,A,T	181323:ref=C:G,A,T	181324:ref=G:C,A,T	181325:ref=G:C,A,T	181326:ref=C:G,A,T	181327:ref=G:C,A,T	181328:ref=C:G,A,T	181329:ref=A:G,C,T	181330:ref=G:C,A,T	181331:ref=G:C,A,T	181332:ref=C:G,A,T	181333:ref=G:C,A,T	181334:ref=C:G,A,T	181335:ref=A:G,C,T	181336:ref=G:C,A,T	181337:ref=A:G,C,T	181338:ref=G:C,A,T	181339:ref=A:G,C,T	181340:ref=C:G,A,T	181341:ref=A:G,C,T	181342:ref=C:G,A,T	181343:ref=A:G,C,T	181344:ref=T:G,C,A	181345:ref=G:C,A,T	181346:ref=C:G,A,T	181347:ref=T:G,C,A	181348:ref=A:G,C,T	181349:ref=G:C,A,T	181350:ref=C:G,A,T	181351:ref=G:C,A,T	181352:ref=C:G,A,T	181353:ref=G:C,A,T	181354:ref=T:G,C,A	181355:ref=C:G,A,T	181356:ref=C:G,A,T	181357:ref=A:G,C,T	181358:ref=G:C,A,T	181359:ref=G:C,A,T	181360:ref=G:C,A,T	181361:ref=G:C,A,T	181362:ref=A:G,C,T	181363:ref=G:C,A,T	181364:ref=G:C,A,T	181365:ref=A:G,C,T	181366:ref=G:C,A,T	181367:ref=G:C,A,T	181368:ref=C:G,A,T	181369:ref=G:C,A,T	181370:ref=T:G,C,A	181371:ref=G:C,A,T	181372:ref=G:C,A,T	181373:ref=C:G,A,T	181374:ref=A:G,C,T	181375:ref=C:G,A,T	181376:ref=A:G,C,T	181377:ref=G:C,A,T	181378:ref=G:C,A,T	181379:ref=C:G,A,T	181380:ref=G:C,A,T	181381:ref=C:G,A,T	181382:ref=A:G,C,T	181383:ref=G:C,A,T	181384:ref=A:G,C,T	181385:ref=G:C,A,T	181386:ref=A:G,C,T	181387:ref=C:G,A,T	181388:ref=A:G,C,T	181389:ref=C:G,A,T	181390:ref=A:G,C,T	181391:ref=T:G,C,A	181392:ref=G:C,A,T	181393:ref=C:G,A,T	181394:ref=T:G,C,A	181395:ref=A:G,C,T	181396:ref=G:C,A,T	181397:ref=C:G,A,T	181398:ref=G:C,A,T	181399:ref=C:G,A,T	181400:ref=G:C,A,T	181401:ref=C:G,A,T	181402:ref=C:G,A,T	181403:ref=C:G,A,T	181404:ref=A:G,C,T	181405:ref=G:C,A,T	181406:ref=G:C,A,T	181407:ref=G:C,A,T	181408:ref=G:C,A,T	181409:ref=A:G,C,T	181410:ref=G:C,A,T	181411:ref=G:C,A,T	181412:ref=A:G,C,T	181413:ref=G:C,A,T	181414:ref=G:C,A,T	181415:ref=C:G,A,T	181416:ref=G:C,A,T	181417:ref=T:G,C,A	181418:ref=G:C,A,T	181419:ref=G:C,A,T	181420:ref=C:G,A,T	181421:ref=G:C,A,T	181422:ref=C:G,A,T	181423:ref=A:G,C,T	181424:ref=G:C,A,T	181425:ref=G:C,A,T	181426:ref=C:G,A,T	181427:ref=G:C,A,T	181428:ref=C:G,A,T	181429:ref=A:G,C,T	181430:ref=G:C,A,T	181431:ref=A:G,C,T	181432:ref=G:C,A,T	181433:ref=A:G,C,T	181434:ref=G:C,A,T	181435:ref=G:C,A,T	181436:ref=C:G,A,T	181437:ref=G:C,A,T	181438:ref=C:G,A,T	181439:ref=G:C,A,T	181440:ref=C:G,A,T	181441:ref=C:G,A,T	181442:ref=G:C,A,T	181443:ref=T:G,C,A	181444:ref=G:C,A,T	181445:ref=C:G,A,T	181446:ref=T:G,C,A	181447:ref=G:C,A,T	181448:ref=C:G,A,T	181449:ref=C:G,A,T	181450:ref=G:C,A,T	181451:ref=C:G,A,T	181452:ref=A:G,C,T	181453:ref=G:C,A,T	181454:ref=G:C,A,T	181455:ref=C:G,A,T	181456:ref=G:C,A,T	181457:ref=C:G,A,T	181458:ref=A:G,C,T	181459:ref=G:C,A,T	181460:ref=A:G,C,T	181461:ref=G:C,A,T	181462:ref=A:G,C,T	181463:ref=C:G,A,T	181464:ref=A:G,C,T	181465:ref=C:G,A,T	181466:ref=A:G,C,T	181467:ref=T:G,C,A	181468:ref=G:C,A,T	181469:ref=C:G,A,T	181470:ref=T:G,C,A	181471:ref=A:G,C,T	181472:ref=G:C,A,T	181473:ref=C:G,A,T	181474:ref=G:C,A,T	181475:ref=C:G,A,T	181476:ref=G:C,A,T	181477:ref=T:G,C,A	181478:ref=C:G,A,T	181479:ref=C:G,A,T	181480:ref=A:G,C,T	181481:ref=G:C,A,T	181482:ref=G:C,A,T	181483:ref=G:C,A,T	181484:ref=G:C,A,T	181485:ref=G:C,A,T	181486:ref=T:G,C,A	181487:ref=G:C,A,T	181488:ref=G:C,A,T	181489:ref=A:G,C,T	181490:ref=G:C,A,T	181491:ref=G:C,A,T	181492:ref=C:G,A,T	181493:ref=G:C,A,T	181494:ref=T:G,C,A	181495:ref=G:C,A,T	181496:ref=G:C,A,T	181497:ref=C:G,A,T	181498:ref=G:C,A,T	181499:ref=C:G,A,T	181500:ref=A:G,C,T	181501:ref=G:C,A,T	181502:ref=G:C,A,T	181503:ref=C:G,A,T	181504:ref=G:C,A,T	181505:ref=C:G,A,T	181506:ref=A:G,C,T	181507:ref=G:C,A,T	181508:ref=A:G,C,T	181509:ref=G:C,A,T	181510:ref=A:G,C,T	181511:ref=C:G,A,T	181512:ref=G:C,A,T	181513:ref=C:G,A,T	181514:ref=A:G,C,T	181515:ref=C:G,A,T	181516:ref=G:C,A,T	181517:ref=C:G,A,T	181518:ref=C:G,A,T	181519:ref=T:G,C,A	181520:ref=A:G,C,T	181521:ref=C:G,A,T	181522:ref=G:C,A,T	181523:ref=G:C,A,T	181524:ref=G:C,A,T	181525:ref=C:G,A,T	181526:ref=G:C,A,T	181527:ref=G:C,A,T	181528:ref=G:C,A,T	181529:ref=G:C,A,T	181530:ref=T:G,C,A	181531:ref=T:G,C,A	181532:ref=G:C,A,T	181533:ref=G:C,A,T	181534:ref=G:C,A,T	181535:ref=G:C,A,T	181536:ref=G:C,A,T	181537:ref=G:C,A,T	181538:ref=G:C,A,T	181539:ref=G:C,A,T	181540:ref=C:G,A,T	181541:ref=G:C,A,T	181542:ref=T:G,C,A	181543:ref=G:C,A,T	181544:ref=T:G,C,A	181545:ref=G:C,A,T	181546:ref=T:G,C,A	181547:ref=T:G,C,A	181548:ref=A:G,C,T	181549:ref=C:G,A,T	181550:ref=A:G,C,T	181551:ref=G:C,A,T	181552:ref=G:C,A,T	181553:ref=A:G,C,T	181554:ref=G:C,A,T	181555:ref=C:G,A,T	181556:ref=A:G,C,T	181557:ref=A:G,C,T	181558:ref=A:G,C,T	181559:ref=G:C,A,T	181560:ref=T:G,C,A	181561:ref=C:G,A,T	181562:ref=G:C,A,T	181563:ref=C:G,A,T	181564:ref=A:G,C,T	181565:ref=C:G,A,T	181566:ref=G:C,A,T	181567:ref=G:C,A,T	181568:ref=C:G,A,T	181569:ref=G:C,A,T	181570:ref=C:G,A,T	181571:ref=C:G,A,T	181572:ref=G:C,A,T	181573:ref=G:C,A,T	181574:ref=G:C,A,T	181575:ref=C:G,A,T	181576:ref=T:G,C,A	181577:ref=G:C,A,T	181578:ref=G:C,A,T	181579:ref=G:C,A,T	181580:ref=G:C,A,T	181581:ref=G:C,A,T	181582:ref=C:G,A,T	181583:ref=G:C,A,T	181584:ref=G:C,A,T	181585:ref=G:C,A,T	181586:ref=G:C,A,T	181587:ref=G:C,A,T	181588:ref=G:C,A,T	181589:ref=G:C,A,T	181590:ref=G:C,A,T	181591:ref=G:C,A,T	181592:ref=G:C,A,T	181593:ref=G:C,A,T	181594:ref=G:C,A,T	181595:ref=G:C,A,T	181596:ref=G:C,A,T	181597:ref=G:C,A,T	181598:ref=G:C,A,T	181599:ref=G:C,A,T	181600:ref=C:G,A,T	181601:ref=G:C,A,T	181602:ref=C:G,A,T	181603:ref=C:G,A,T	181604:ref=G:C,A,T	181605:ref=T:G,C,A	181606:ref=G:C,A,T	181607:ref=C:G,A,T	181608:ref=A:G,C,T	181609:ref=C:G,A,T	181610:ref=G:C,A,T	181611:ref=C:G,A,T	181612:ref=G:C,A,T	181613:ref=C:G,A,T
chr1:267925-268171	267925:ref=A:G,C,A,T	267926:ref=A:G,C,T	267927:ref=G:C,A,T	267928:ref=G:C,A,T	267929:ref=G:C,A,T	267930:ref=T:G,C,A	267931:ref=T:G,C,A	267932:ref=G:C,A,T	267933:ref=C:G,A,T	267934:ref=T:G,C,A	267935:ref=T:G,C,A	267936:ref=G:C,A,T	267937:ref=A:G,C,T	267938:ref=C:G,A,T	267939:ref=C:G,A,T	267940:ref=C:G,A,T	267941:ref=A:G,C,T	267942:ref=C:G,A,T	267943:ref=A:G,C,T	267944:ref=G:C,A,T	267945:ref=A:G,C,T	267946:ref=T:G,C,A	267947:ref=G:C,A,T	267948:ref=T:G,C,A	267949:ref=G:C,A,T	267950:ref=A:G,C,T	267951:ref=A:G,C,T	267952:ref=G:C,A,T	267953:ref=C:G,A,T	267954:ref=T:G,C,A	267955:ref=G:C,A,T	267956:ref=A:G,C,T	267957:ref=G:C,A,T	267958:ref=G:C,A,T	267959:ref=C:G,A,T	267960:ref=T:G,C,A	267961:ref=G:C,A,T	267962:ref=A:G,C,T	267963:ref=A:G,C,T	267964:ref=G:C,A,T	267965:ref=G:C,A,T	267966:ref=A:G,C,T	267967:ref=G:C,A,T	267968:ref=A:G,C,T	267969:ref=C:G,A,T	267970:ref=T:G,C,A	267971:ref=G:C,A,T	267972:ref=A:G,C,T	267973:ref=T:G,C,A	267974:ref=G:C,A,T	267975:ref=T:G,C,A	267976:ref=G:C,A,T	267977:ref=G:C,A,T	267978:ref=T:G,C,A	267979:ref=T:G,C,A	267980:ref=T:G,C,A	267981:ref=C:G,A,T	267982:ref=T:G,C,A	267983:ref=C:G,A,T	267984:ref=C:G,A,T	267985:ref=T:G,C,A	267986:ref=C:G,A,T	267987:ref=A:G,C,T	267988:ref=G:C,A,T	267989:ref=T:G,C,A	267990:ref=T:G,C,A	267991:ref=T:G,C,A	267992:ref=C:G,A,T	267993:ref=T:G,C,A	267994:ref=C:G,A,T	267995:ref=T:G,C,A	267996:ref=G:C,A,T	267997:ref=T:G,C,A	267998:ref=G:C,A,T	267999:ref=C:G,A,T	268000:ref=A:G,C,T	268001:ref=G:C,A,T	268002:ref=C:G,A,T	268003:ref=A:G,C,T	268004:ref=C:G,A,T	268005:ref=C:G,A,T	268006:ref=A:G,C,T	268007:ref=G:C,A,T	268008:ref=G:C,A,T	268009:ref=T:G,C,A	268010:ref=G:C,A,T	268011:ref=G:C,A,T	268012:ref=C:G,A,T	268013:ref=A:G,C,T	268014:ref=G:C,A,T	268015:ref=C:G,A,T	268016:ref=A:G,C,T	268017:ref=G:C,A,T	268018:ref=A:G,C,T	268019:ref=G:C,A,T	268020:ref=G:C,A,T	268021:ref=T:G,C,A	268022:ref=C:G,A,T	268023:ref=A:G,C,T	268024:ref=G:C,A,T	268025:ref=C:G,A,T	268026:ref=A:G,C,T	268027:ref=A:G,C,T	268028:ref=G:C,A,T	268029:ref=G:C,A,T	268030:ref=C:G,A,T	268031:ref=A:G,C,T	268032:ref=A:G,C,T	268033:ref=A:G,C,T	268034:ref=C:G,A,T	268035:ref=C:G,A,T	268036:ref=C:G,A,T	268037:ref=G:C,A,T	268038:ref=A:G,C,T	268039:ref=G:C,A,T	268040:ref=C:G,A,T	268041:ref=C:G,A,T	268042:ref=C:G,A,T	268043:ref=G:C,A,T	268044:ref=G:C,A,T	268045:ref=G:C,A,T	268046:ref=G:C,A,T	268047:ref=A:G,C,T	268048:ref=T:G,C,A	268049:ref=G:C,A,T	268050:ref=C:G,A,T	268051:ref=G:C,A,T	268052:ref=G:C,A,T	268053:ref=A:G,C,T	268054:ref=G:C,A,T	268055:ref=T:G,C,A	268056:ref=G:C,A,T	268057:ref=G:C,A,T	268058:ref=G:C,A,T	268059:ref=G:C,A,T	268060:ref=G:C,A,T	268061:ref=C:G,A,T	268062:ref=A:G,C,T	268063:ref=G:C,A,T	268064:ref=C:G,A,T	268065:ref=T:G,C,A	268066:ref=A:G,C,T	268067:ref=C:G,A,T	268068:ref=G:C,A,T	268069:ref=T:G,C,A	268070:ref=C:G,A,T	268071:ref=C:G,A,T	268072:ref=T:G,C,A	268073:ref=C:G,A,T	268074:ref=T:G,C,A	268075:ref=C:G,A,T	268076:ref=T:G,C,A	268077:ref=T:G,C,A	268078:ref=G:C,A,T	268079:ref=A:G,C,T	268080:ref=G:C,A,T	268081:ref=C:G,A,T	268082:ref=T:G,C,A	268083:ref=A:G,C,T	268084:ref=C:G,A,T	268085:ref=A:G,C,T	268086:ref=G:C,A,T	268087:ref=C:G,A,T	268088:ref=A:G,C,T	268089:ref=G:C,A,T	268090:ref=A:G,C,T	268091:ref=T:G,C,A	268092:ref=T:G,C,A	268093:ref=C:G,A,T	268094:ref=A:G,C,T	268095:ref=C:G,A,T	268096:ref=T:G,C,A	268097:ref=C:G,A,T	268098:ref=T:G,C,A	268099:ref=G:C,A,T	268100:ref=T:G,C,A	268101:ref=T:G,C,A	268102:ref=C:G,A,T	268103:ref=T:G,C,A	268104:ref=G:C,A,T	268105:ref=T:G,C,A	268106:ref=T:G,C,A	268107:ref=T:G,C,A	268108:ref=C:G,A,T	268109:ref=A:G,C,T	268110:ref=T:G,C,A	268111:ref=T:G,C,A	268112:ref=G:C,A,T	268113:ref=T:G,C,A	268114:ref=T:G,C,A	268115:ref=G:C,A,T	268116:ref=T:G,C,A	268117:ref=T:G,C,A	268118:ref=T:G,C,A	268119:ref=A:G,C,T	268120:ref=G:C,A,T	268121:ref=T:G,C,A	268122:ref=T:G,C,A	268123:ref=T:G,C,A	268124:ref=G:C,A,T	268125:ref=C:G,A,T	268126:ref=G:C,A,T	268127:ref=T:G,C,A	268128:ref=T:G,C,A	268129:ref=G:C,A,T	268130:ref=T:G,C,A	268131:ref=G:C,A,T	268132:ref=T:G,C,A	268133:ref=T:G,C,A	268134:ref=T:G,C,A	268135:ref=C:G,A,T	268136:ref=T:G,C,A	268137:ref=C:G,A,T	268138:ref=C:G,A,T	268139:ref=A:G,C,T	268140:ref=A:G,C,T	268141:ref=C:G,A,T	268142:ref=T:G,C,A	268143:ref=T:G,C,A	268144:ref=T:G,C,A	268145:ref=G:C,A,T	268146:ref=T:G,C,A	268147:ref=G:C,A,T	268148:ref=C:G,A,T	268149:ref=C:G,A,T	268150:ref=T:G,C,A	268151:ref=C:G,A,T	268152:ref=A:G,C,T	268153:ref=T:G,C,A	268154:ref=C:G,A,T	268155:ref=A:G,C,T	268156:ref=G:C,A,T	268157:ref=G:C,A,T	268158:ref=A:G,C,T	268159:ref=A:G,C,T	268160:ref=A:G,C,T	268161:ref=A:G,C,T	268162:ref=G:C,A,T	268163:ref=C:G,A,T	268164:ref=T:G,C,A	268165:ref=T:G,C,A	268166:ref=T:G,C,A	268167:ref=G:C,A,T	268168:ref=G:C,A,T	268169:ref=A:G,C,T	268170:ref=T:G,C,A

In [5]:
import pandas as pd
import vcfpy
import sys
import gzip


with gzip.open("/hpc/home/rv103/igvf/IGVF-DACC/IGVFFI2231RETG.vcf.gz", "r") as infile, open('/hpc/home/rv103/igvf/revathy/IGVF_predictions/data/Y2AVE_variants.txt',"wt") as outfile:
    for line in infile:
        line = line.decode("utf-8")
        if line.startswith("#") == False:
            record = line.strip().split("\t")
            chrom = record[0]
            pos = str(int(record[1])-1) # convert 1-based index to 0-based index to fit 2bittofa
            ref = record[3].upper()
            alt = record[4].upper()
            out = chrom+':'+pos+':'+'ref='+ref+':'+ref+','+alt+'\n'
            outfile.write(out)

    outfile.close()

26664185

In [2]:
%%writefile /hpc/home/rv103/igvf/revathy/notebooks/runtime.py
import gzip
from collections import defaultdict

vcf_path = "/hpc/home/rv103/igvf/IGVF-DACC/IGVFFI2231RETG.vcf.gz"

# Store: key = (chrom, pos, ref), value = set of ALT alleles observed
site_alts = defaultdict(set)

with gzip.open(vcf_path, "rt") as infile:
    for line in infile:
        if line.startswith("#"):
            continue

        record = line.strip().split("\t")

        chrom = record[0]
        pos = record[1]             # keep as string
        ref = record[3].upper()
        alts = record[4].upper().split(",")  # should be single alt per row in your file

        key = (chrom, pos, ref)

        # Add all ALT alleles (even though each row should contain only 1)
        for a in alts:
            if a != ".":
                site_alts[key].add(a)

# ---- Counting ----

num_unique_variants = len(site_alts)
ref_count = num_unique_variants               # 1 REF per unique site
alt_count = sum(len(a) for a in site_alts.values())

print("Unique variant sites:", num_unique_variants)
print("Total REF alleles:", ref_count)
print("Total ALT alleles:", alt_count)

Writing /hpc/home/rv103/igvf/revathy/notebooks/runtime.py

In [1]:

24822435+26663680

51486115